apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service-deployment
  labels:
    app: api-gateway-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service-deployment
  template:
    metadata:
      labels:
        app: api-gateway-service-deployment
    spec:
      containers:
        - name: api-gateway-service-deployment
          image: asamatdev/sh-api-gateway-service:replaceImageTag
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sh-config-maps
            - secretRef:
                name: sh-secrets
          resources:
            requests:
              memory: "30Mi"
            limits:
              memory: "50Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway-service-deployment
  ports:
    - port: 8080
      targetPort: 8080